### ISSUE TITLE
README - add list of commands to see this in action

### ISSUE THREAD

**Issue by rsvoboda** [wildfly/wildfly-galleon-pack-template#1]
README starts with quite a complex "Project structure" section. This is quite discouraging to proceed with reading.

The first section in README should provide a simple way to start playing with this.  For example, there should be a list of commands to see this in action, something like this (guessing, haven't tried yet)
```
mvn clean install
./build/target/wildfly-18.0.1.Final-template-1.0.0.Alpha-SNAPSHOT/bin/standalone.sh &
mvn package wildfly:deploy -pl example
curl ....
./build/target/wildfly-18.0.1.Final-template-1.0.0.Alpha-SNAPSHOT/bin/jboss-cli.sh -c shutdown
```

**Comment by kabir** [comment]
I'll try to re-jig things a bit next week
